package com.felysoft.felysoftApp.util;

public enum Permission {
    READ_ALL_PRODUCTS,
    READ_ONE_PRODUCT,
    CREATE_ONE_PRODUCT,
    UPDATE_ONE_PRODUCT,
    DISABLE_ONE_PRODUCT,

    READ_ALL_CATEGORIES,
    READ_ONE_CATEGORY,
    CREATE_ONE_CATEGORY,
    UPDATE_ONE_CATEGORY,
    DISABLE_ONE_CATEGORY,
    READ_CATEGORIES_BY_PROVIDER,
    ASSOCIATE_CATEGORY_PROVIDER,

    READ_ALL_PROVIDERS,
    READ_ONE_PROVIDER,
    CREATE_ONE_PROVIDER,
    UPDATE_ONE_PROVIDER,
    DISABLE_ONE_PROVIDER,
    READ_PROVIDERS_BY_CATEGORY,

    READ_ALL_SERVICES,
    READ_ONE_SERVICE,
    CREATE_ONE_SERVICE,
    UPDATE_ONE_SERVICE,
    DISABLE_ONE_SERVICE,

    READ_ALL_TYPE_SERVICES,
    READ_ONE_TYPE_SERVICE,
    CREATE_ONE_TYPE_SERVICE,
    UPDATE_ONE_TYPE_SERVICE,
    DISABLE_ONE_TYPE_SERVICE,

    READ_ALL_GENRES,
    READ_ONE_GENRE,
    CREATE_ONE_GENRE,
    UPDATE_ONE_GENRE,
    DISABLE_ONE_GENRE,
    READ_GENRES_BY_AUTHOR,
    ASSOCIATE_GENRE_AUTHOR,

    READ_ALL_AUTHORS,
    READ_ONE_AUTHOR,
    CREATE_ONE_AUTHOR,
    UPDATE_ONE_AUTHOR,
    DISABLE_ONE_AUTHOR,
    READ_AUTHORS_BY_GENRE,

    READ_ALL_BOOKS,
    READ_ONE_BOOK,
    CREATE_ONE_BOOK,
    UPDATE_ONE_BOOK,
    DISABLE_ONE_BOOK,
    READ_INVENTORY_BOOKS,

    READ_ALL_CHARGES,
    READ_ONE_CHARGE,
    CREATE_ONE_CHARGE,
    UPDATE_ONE_CHARGE,
    DISABLE_ONE_CHARGE,

    READ_ALL_USERS,
    READ_ONE_USER,
    CREATE_ONE_USER,
    UPDATE_ONE_USER,
    DISABLE_ONE_USER,

    READ_MY_PROFILE
}
