package com.felysoft.felysoftApp.util;

public enum Permission {
    READ_ALL_PRODUCTS,
    READ_ONE_PRODUCT,
    CREATE_ONE_PRODUCT,
    UPDATE_ONE_PRODUCT,
    DISABLE_ONE_PRODUCT,
    READ_INVENTORY_PRODUCTS,

    READ_ALL_CATEGORIES,
    READ_ONE_CATEGORY,
    CREATE_ONE_CATEGORY,
    UPDATE_ONE_CATEGORY,
    DISABLE_ONE_CATEGORY,
    READ_CATEGORIES_BY_PROVIDER,
    ASSOCIATE_CATEGORY_PROVIDER,

    READ_ALL_PROVIDERS,
    READ_ONE_PROVIDER,
    CREATE_ONE_PROVIDER,
    UPDATE_ONE_PROVIDER,
    DISABLE_ONE_PROVIDER,
    READ_PROVIDERS_BY_CATEGORY,

    READ_ALL_SERVICES,
    READ_ONE_SERVICE,
    CREATE_ONE_SERVICE,
    UPDATE_ONE_SERVICE,
    DISABLE_ONE_SERVICE,

    READ_ALL_TYPE_SERVICES,
    READ_ONE_TYPE_SERVICE,
    CREATE_ONE_TYPE_SERVICE,
    UPDATE_ONE_TYPE_SERVICE,
    DISABLE_ONE_TYPE_SERVICE,

    READ_ALL_GENRES,
    READ_ONE_GENRE,
    CREATE_ONE_GENRE,
    UPDATE_ONE_GENRE,
    DISABLE_ONE_GENRE,
    READ_GENRES_BY_AUTHOR,
    ASSOCIATE_GENRE_AUTHOR,

    READ_ALL_AUTHORS,
    READ_ONE_AUTHOR,
    CREATE_ONE_AUTHOR,
    UPDATE_ONE_AUTHOR,
    DISABLE_ONE_AUTHOR,
    READ_AUTHORS_BY_GENRE,

    READ_ALL_BOOKS,
    READ_ONE_BOOK,
    CREATE_ONE_BOOK,
    UPDATE_ONE_BOOK,
    DISABLE_ONE_BOOK,
    READ_INVENTORY_BOOKS,

    READ_ALL_CHARGES,
    READ_ONE_CHARGE,
    CREATE_ONE_CHARGE,
    UPDATE_ONE_CHARGE,
    DISABLE_ONE_CHARGE,

    READ_ALL_EMPLOYEES,
    READ_ONE_EMPLOYEE,
    CREATE_ONE_EMPLOYEE,
    UPDATE_ONE_EMPLOYEE,
    DISABLE_ONE_EMPLOYEE,

    READ_ALL_PAYMENTS,
    READ_ONE_PAYMENT,
    CREATE_ONE_PAYMENT,
    UPDATE_ONE_PAYMENT,
    DISABLE_ONE_PAYMENT,

    READ_ALL_DETAILS,
    READ_ONE_DETAIL,
    CREATE_ONE_DETAIL,
    UPDATE_ONE_DETAIL,
    DISABLE_ONE_DETAIL,

    READ_ALL_EXPENSES,
    READ_ONE_EXPENSE,
    CREATE_ONE_EXPENSE,
    UPDATE_ONE_EXPENSE,
    DISABLE_ONE_EXPENSE,

    READ_ALL_SALES,
    READ_ONE_SALE,
    CREATE_ONE_SALE,
    UPDATE_ONE_SALE,
    DISABLE_ONE_SALE,

    READ_ALL_RESERVES,
    READ_ONE_RESERVE,
    CREATE_ONE_RESERVE,
    UPDATE_ONE_RESERVE,
    DISABLE_ONE_RESERVE,

    READ_ALL_PURCHASES,
    READ_ONE_PURCHASE,
    CREATE_ONE_PURCHASE,
    UPDATE_ONE_PURCHASE,
    DISABLE_ONE_PURCHASE,
    READ_EXPENSE_BY_PURCHASE, //

    READ_ALL_USERS,
    READ_ONE_USER,
    CREATE_ONE_USER,
    UPDATE_ONE_USER,
    DISABLE_ONE_USER,

    READ_MY_PROFILE
}
